baseURL = 'https://0ccu.lt/'
languageCode = 'en-us'
title = '0ccu.lt'
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

copyright = "greetings from [renavi](https://ren.0ccu.lt) and the inner circle."
description = "The 0ccult is the home of the occult."

[author]
  name = "0ccu.lt"
  headline = "The `0c`cult is the home of the occult."
  image = "sigil.png"
  links = [
    { self = { href = "https://ren.0ccu.lt", text = "Self" }},
    { home = { href = "https://starrypoint.me", text = "Home" } },
    { work = { href = "https://whistler.page", text = "Work" } },
    { projects = { href = "/projects", text = "Project", target = "_self" } },
    { socials = { href = "/socials", text = "Social", target = "_self" } },
  ]

[params]
  attribution = false
  description = "The 0ccult is the home of the occult."

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
